apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: photon
  namespace: photon
  labels:
    app: photon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photon
  template:
    metadata:
      labels:
        app: photon
    spec:
      terminationGracePeriodSeconds: 25
      affinity:
        nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 1
                preference:
                  matchExpressions:
                  - key: cloud.google.com/gke-spot
                    operator: Equal
                    values:
                    - true
      containers:
        - image: gcr.io/voxelphile/github.com/voxelphile/photon
          imagePullPolicy: IfNotPresent
          name: photon-sha256-1
          resources:
            limits:
              cpu: "0.05"
              memory: "128Mi"
            requests:
              cpu: "0.05"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: photon # Sets service name
  labels:
    app: photon # Labels and Selectors
spec:
  type: NodePort # Sets service type
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      nodePort: 32323
  selector:
    app: photon