apiVersion: v1
kind: Namespace
metadata:
  name: photon
  labels:
    name: photon
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: photon-config
  namespace: photon
  labels:
    app: photon
data:
  PHOTON_STRATEGY: host 
  DB_IP: 10.92.1.0
---
apiVersion: v1
kind: "Deployment"
metadata:
  name: photon
  namespace: photon
  labels:
    app: photon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photon
  template:
    metadata:
      labels:
        app: photon
    spec:
      terminationGracePeriodSeconds: 25
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-spot
                operator: In
                values:
                - "true"
      containers:
        - image: gcr.io/voxelphile/github.com/voxelphile/photon
          imagePullPolicy: IfNotPresent
          name: photon-sha256-1
          resources:
            limits:
              cpu: "0.05"
              memory: "128Mi"
            requests:
              cpu: "0.05"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: photon # Sets service name
  labels:
    app: photon # Labels and Selectors
spec:
  type: NodePort # Sets service type
  ports:
    - name: photon
      port: 5432
      targetPort: 5432 # rando
      nodePort: 31111
  selector:
    app: photon